language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - pip install -e .
script:
  - py.test --cov-config .coveragerc --cov=letssync
after_success:
  - coveralls
